server:
  port: 8080

management:
  endpoints.web.exposure.include: health,info
  endpoint.health.show-details: never

logging:
  level:
    root: INFO
    org.apache.camel: ERROR

spring:
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      client-type: lettuce