server:
  port: 8080

management:
  endpoints.web.exposure.include: health,info
  endpoint.health.show-details: never

logging:
  level:
    root: DEBUG
    org.apache.camel: DEBUG

spring:
  datasource:
    url: ${DB_URL:jdbc:sqlite:/var/sqlite/files.db}
    driver-class-name: org.sqlite.JDBC
    #username: ${DB_USERNAME:}
    #password: ${DB_PASSWORD:}
  sql:
    init:
      mode: never
